config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions

  get "quiz/index"
  post "quiz/start"
  get "quiz/question"
  post "quiz/question"
  post "quiz/answer"
  get "quiz/end"
  post "choices/create"
  post "choices/destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :choices

  def uncorrect
    choices.each {|c| c.correct = false}
  end

  def answer
    uncorrect
    choices.select{|c| c.correct}[0]
  end

  def answer= choice
    if !answer.nil?
      answer.correct = false
    end
    if choices.include? choice
      choice.correct = true
    else
      choices << choice
      choice.correct = true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def create
    @question = Question.find(params[:question])
    text = params[:text]
    correct = params[:correct]
    new = Choice.create(:text => text, :correct => correct, :question_id => @question.id)

    if new.correct
      @question.answer = new
    end

    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question])
    @choice = Choice.find(params[:choice])
    @choice.destroy

    redirect_to question_path(@question)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @questions.sort {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html
      format.xml {render :xml => @questions}
    end
  end

  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  def new
    @question = Question.new

    respond_to do |format|
      format.html
      format.xml {render :xml => @question}
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(params_question)
    respond_to do |format|
      if @question.save
        format.html {redirect_to(@question, :notice => 'Pregunta agregada exitosamente.')}
        format.xml {render :xml => @question, :status => :created, :locaction => @question}

      end
    end
  end

  def update
    @question = Question.find(params[:id])
    respond_to do |format|
      if @question.update_attributes(params_question)
        format.html {redirect_to(@question, :notice => 'Pregunta actualizada exitosamente')}
        format.xml { head :ok}
      else
        format.html {render :action => 'edit'}
        format.xml {render :xml => @question.errors, :status => :unprocessable_entity}
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_path)}
      format.xml {head :ok}
    end
  end

  private
  def params_question
    params.require(:question).permit(:text)
  end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end

  def start
    total = params[:number].to_i
    all = Question.all.map{|x| x.id}
    session[:questions] = all.sort_by{rand}[0..(total-1)]
    session[:total] = total
    session[:current] = 0
    session[:correct] = 0
    redirect_to :action => 'question'
  end

  def question
    @current = session[:current]
    @total = session[:total]
    if @current >= @total
      redirect_to :action => 'end'
      return
    end
    @question = Question.find(session[:questions][@current])
    @choices = @question.choices.sort_by {rand}
    session[:question] = @question
    session[:choices] = @choices
  end

  def answer
    @current = session[:current]
    @total = session[:total]
    choiceid = params[:choice]
    @question = session[:question]
    @choices = session[:choices]
    @choice = choiceid ? Choice.find(choiceid):nil
    if @choice and @choice.correct
      @correct = true
      session[:correct] += 1
    else
      @correct = false
    end
    session[:current] += 1 
  end

  def end
    @correct = session[:correct]
    @total = session[:total]
    @score = @correct * 100 / @total
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/choices/create.html.erb
<h1>Choices#create</h1>
<p>Find me in app/views/choices/create.html.erb</p>

app/views/choices/destroy.html.erb
<h1>Choices#destroy</h1>
<p>Find me in app/views/choices/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb

<%= form_for(@question) do |f| %>
<% if @question.errors.any? %>
<div id="error_explanation">
  <h2> <%= pluralize(@question.errors.count, 'error') %>
  prohibited this question from begin saved:
  </h2>

  <ul>
    <% @question.errors.full_messages.each do |msg| %>
    <li><%=msg%></li>
      <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :text %><br/>
  <%= f.text_area :text, :size => '50x3', :class => "form-control" %>
</div>
<div class="actions">
  <%= f.submit :class => "btn btn-primary" %>
</div>
<% end %>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<div class="container">
<h1>Editing question</h1>
<%= render 'form' %>
<%= link_to 'Show', @question, :class => "btn btn-default" %>
<%= link_to 'Back', questions_path, :class => "btn btn-default" %>
<% content_for(:title) do %>
Edit Question
<% end %>
</div>

app/views/questions/index.html.erb
<div class="container">
<h1>Listing question</h1>
<p>Total: <%= @questions.size %></p>
<p><%= link_to 'New Question', new_question_path, :class => "btn btn-primary", :style => "color:white" %></p>
<table border="1" class="table table-bored table-hover">
  <tr>
    <th>Text</th>
    <th>Choices</th>
    <th colspan="3">Opciones</th>
  </tr>
  <% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.choices.each do |choice| %>
        <li>
          <%= choice.text %>
          <% if choice.correct == "1".to_i %>(Correct)<% end %>
        </li>
          <% end %>
      </ul>
    </td>
    <td> <%= link_to 'Show', question, :class => "btn btn-default" %></td>
    <td><%= link_to 'Edit', edit_question_path(question), :class => "btn btn-default" %></td>
    <td><%= link_to 'Destroy', question, :class => "btn btn-danger", :style => "color:white;", :confirm => '¿Estas seguro?', :method => :delete %></td>
  </tr>
    <% end %>
</table>
<% content_for(:title) do %>
All questions
<% end %>
</div>

app/views/questions/new.html.erb
<div class="container">
<h1>New Question</h1>
<%= render 'form' %>
<%= link_to 'Back', questions_path, :class => "btn btn-default" %>
<% content_for(:title) do %>
New Question
<% end %>
</div>

app/views/questions/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<h3><strong>Text:</strong>
  <%= @question.text %></h3>
  <hr>
  
<h4>Choices</h4>
<table border="1" class="table table-bored table-hover">
  <tr>
    <th>Choice</th>
    <th>Opciones</th>
  </tr>

  <% @question.choices.find_each do |choice| %>
  
  <tr>
    <td><%= choice.text %><% if choice.correct %>(Correct)<% end %></td>
    <%= form_tag({:controller => 'choices', :action => 'destroy'}) do %>
    <%= hidden_field_tag :question, @question.id %>
    <%= hidden_field_tag :choice, choice.id %>
    <td><%= submit_tag 'Delete', :class => "btn btn-danger"%></td>
  </tr>
<% end %>
<% end %>

</table>
<hr>
<h5><strong>New choice</strong></h5>
<%= form_tag({:controller => 'choices', :action => 'create'}) do %>
<%= hidden_field_tag :question, @question.id %>
  <div class="input-group">
  <%= label_tag 'Text' %><br />
  <%= text_field_tag :text, "",:class => "form-control"%>
  </div>
  <%= check_box_tag :correct %><br />
  
  <%= submit_tag 'Create', :class => "btn btn-primary" %>
<% end %>
<br/>
<%= link_to 'Edit', edit_question_path(@question), :class => "btn btn-default" %>
<%= link_to 'Back', questions_path, :class => "btn btn-default"  %>
<% content_for(:title) do %>
  Question Details
<% end %>
</div>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>

app/views/quiz/answer.html.erb
<div class="container">

<h1>Question <%= @current + 1%> of <%= @total %></h1>
<p id="question">
  <%= @question[:text] %>
</p>
<div id="feedback-choices">
  <% @choices.each do |choice| %>
  <% if(choice[:correct]) %>
    <p class="correct feedback-choice">
  <% elsif choice == @choice %>
    <p class="incorrect feedback-choice">
  <% else %>
    <p class="feedback-choice">
  <% end %>
  <%= choice[:text] %>
  </p>
  <% end %>
</div>

  <% if @correct %>
  <div class="alert alert-success">
  <h4>Correct!</h4>
  <% else %>
  <div class="alert alert-danger">
  <h4>Incorrect!</h4>
  <% end %>
</div>
<%= form_tag({:controller => 'quiz', :action => 'question'}) do %>
<div class="center">
  <%= submit_tag('Continue', :class => 'submit btn btn-primary') %>
</div>
<% end %>
<% content_for(:title) do %>
Question <%= @current + 1 %> of <%= @total %>
<% end %>
</div>

app/views/quiz/end.html.erb
<div class="container">

<h1>Quiz Results</h1>
<p id="question">You answered correctly <%= @correct %> out of <%= @total %> questions. </p>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<%= @score %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @score %>%">
  </div>
</div>
<div class="alert alert-info" role="alert"><p id="score"><%= @score %>%</p></div>



<%= form_tag({:controller => 'quiz', :action => 'index'}, :method => 'get') do %>
<div class="center">
  <%= submit_tag('Take another quiz', :class => 'submit btn btn-primary') %>
</div>
<% end %>
<% content_for(:title) do %>
Quiz Results
<% end %>
</div>

app/views/quiz/index.html.erb
<div class="container">
<h1>Start Quiz</h1>
<%= form_tag({:controller => 'quiz', :action => 'start'}) do %>
<p><%= label_tag(:number, 'How many questions do you want in the quiz?', :id => 'question') %></p>
<p class="center">
  <%= select_tag(:number, options_for_select((1..10).map{|x|[x,x]}), :id => 'count', :class => "btn btn-default dropdown-toggle") %>
</p>
<div class="center">
  <%= submit_tag 'Start!', :class => 'submit btn btn-primary' %>
</div>
<% end %>
<% content_for(:title) do %>
Start Quiz
<% end %>
</div>

app/views/quiz/question.html.erb
<div class="container">

<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<%= form_tag({:controller => 'quiz', :action => 'answer'}) do %>
<% @choices.each do |choice| %>
<p class="choice">
  <%= radio_button_tag(:choice, choice.id) %>
  <%= label_tag('choice_'.concat(choice.id.to_s).to_sym, choice.text) %>
</p>
<% end %>
<div class="center">
  <%= submit_tag('Continue', :class => 'submit btn btn-primary') %>
</div>
<% end %>
<% content_for(:title) do %>
Question <%= @current +1 %> of <%= @total %>
<% end %>
</div>

app/views/quiz/start.html.erb
<div class="container">
<h1>Quiz#start</h1>
<p>Find me in app/views/quiz/start.html.erb</p>
</div>